// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-7jcMTmJTlTzVbVqLLCmx2Ru-psJrNdE',
    appId: '1:988841881321:web:23cb2dab9cb62d0556ca78',
    messagingSenderId: '988841881321',
    projectId: 'threadhive-9765c',
    authDomain: 'threadhive-9765c.firebaseapp.com',
    storageBucket: 'threadhive-9765c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9BMRO6LsV9fJv75jYbw6vHFjUB97gk9I',
    appId: '1:988841881321:android:6507376e1f72528356ca78',
    messagingSenderId: '988841881321',
    projectId: 'threadhive-9765c',
    storageBucket: 'threadhive-9765c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBt3kcASqNlHSOyYSA80wIfr9sTUJZpW64',
    appId: '1:988841881321:ios:1ebb60071fbf3f0f56ca78',
    messagingSenderId: '988841881321',
    projectId: 'threadhive-9765c',
    storageBucket: 'threadhive-9765c.firebasestorage.app',
    iosBundleId: 'com.example.redditClone',
  );
}
